<?php
/**
 * @file commerce_autopay.module
 * Provides recurring framework for Drupal Commerce
 */

/**
 * Implements hook_menu().
*/
function commerce_autopay_menu() {
  $items = array();
  $items['admin/commerce/config/recurring'] = array(
    'title' => 'Recurring Orders',
    'file' => 'commerce_autopay.admin.inc',
    'access arguments' => array('administer commerce recurring'),
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('commerce_autopay_admin_form')
  );
  return $items;
}

/**
 * Implements hook_permission()
*/
function commerce_autopay_permission() {
  return array(
    'administer commerce recurring' => array(
      'title' => t('Administer Commerce Recurring')
    )
  );
}

/**
 * Implements hook_help().
 */
function commerce_autopay_help($path, $arg) {
  switch ($path) {
    case 'admin/help#commerce_autopay':
      return t("Provides recurring payment options for Drupal Commerce");
  }
}

/**
 * Implements hook_views_api().
 */
function commerce_autopay_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'commerce_autopay') . '/includes/views',
  );
}


/**
 * Implements hook_entity_info_alter()
*/
function commerce_autopay_entity_info_alter() {
  $entity_info['commerce_order']['bundles']['recurring_order'] = array(
    'label' => t('Recurring Order', array(), array('context' => 'a recurring drupal commerce order')),
  );
}